# Generated by Django 4.2.1 on 2023-05-19 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0003_alter_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='users_disliked',
            field=models.ManyToManyField(blank=True, related_name='users_disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='users_liked',
            field=models.ManyToManyField(blank=True, related_name='users_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
