# Generated by Django 4.2.1 on 2023-05-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_remove_comment_comment_comment_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_disliked',
            new_name='users_disliked',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_liked',
            new_name='users_liked',
        ),
    ]
